<?xml version="1.0"?>
<package format="3">
  <name>genbot_control</name>
  <version>0.1.0</version>
  <description>GenBot control nodes including Ackermann steering</description>
  <maintainer email="zhangshuaiqing@gmail.com">Shuaiqing Zhang</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclpy</depend>
  <depend>geometry_msgs</depend>
  <depend>std_msgs</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
